-- Run this once in the Supabase SQL Editor while authenticated users are allowed
-- to create the source records and workflow records generated by Upload Evidence.
drop policy if exists "authenticated users can manage vehicles" on public.vehicles;
create policy "authenticated users can manage vehicles"
on public.vehicles for all to authenticated
using (true) with check (true);

drop policy if exists "authenticated users can manage cameras" on public.cameras;
create policy "authenticated users can manage cameras"
on public.cameras for all to authenticated
using (true) with check (true);

drop policy if exists "authenticated users can create incidents" on public.incidents;
create policy "authenticated users can create incidents"
on public.incidents for insert to authenticated
with check (true);

drop policy if exists "authenticated users can create detections" on public.detections;
create policy "authenticated users can create detections"
on public.detections for insert to authenticated
with check (true);

drop policy if exists "authenticated users can manage complaints" on public.complaints;
create policy "authenticated users can manage complaints"
on public.complaints for all to authenticated
using (true) with check (true);

drop policy if exists "authenticated users can create complaint events" on public.complaint_events;
create policy "authenticated users can create complaint events"
on public.complaint_events for insert to authenticated
with check (true);

drop policy if exists "authenticated users can manage evidence" on public.evidence;
create policy "authenticated users can manage evidence"
on public.evidence for all to authenticated
using (true) with check (true);