import {
  Camera,
  Complaint,
  Detection,
  Incident,
  PipelineState,
} from './types';

const minsAgo = (m: number) => new Date(Date.now() - m * 60 * 1000).toISOString();
const hoursAgo = (h: number) => new Date(Date.now() - h * 60 * 60 * 1000).toISOString();

export const fullPipeline = (upTo: keyof PipelineState): PipelineState => {
  const order: (keyof PipelineState)[] = [
    'detection',
    'privacy',
    'duplicate',
    'location',
    'authority',
    'complaint',
    'resolution',
  ];
  const idx = order.indexOf(upTo);
  const p: PipelineState = {
    detection: false,
    privacy: false,
    duplicate: false,
    location: false,
    authority: false,
    complaint: false,
    resolution: false,
  };
  order.forEach((k, i) => {
    p[k] = i <= idx;
  });
  return p;
};

export const cameras: Camera[] = [
  {
    id: 'CAM-01',
    vehicleId: 'BUS-204',
    position: 'front',
    route: 'NH-27',
    status: 'online',
    fps: 24,
    lastActive: minsAgo(0),
    installedAt: '2025-11-02',
  },
  {
    id: 'CAM-02',
    vehicleId: 'BUS-118',
    position: 'front',
    route: 'MG Road',
    status: 'online',
    fps: 22,
    lastActive: minsAgo(1),
    installedAt: '2025-10-18',
  },
  {
    id: 'CAM-03',
    vehicleId: 'BUS-091',
    position: 'front',
    route: 'Ring Road',
    status: 'offline',
    fps: 0,
    lastActive: hoursAgo(6),
    installedAt: '2025-09-04',
  },
  {
    id: 'CAM-04',
    vehicleId: 'BUS-204',
    position: 'rear',
    route: 'NH-27',
    status: 'online',
    fps: 26,
    lastActive: minsAgo(0),
    installedAt: '2025-11-02',
  },
  {
    id: 'CAM-05',
    vehicleId: 'BUS-332',
    position: 'front',
    route: 'Airport Road',
    status: 'online',
    fps: 23,
    lastActive: minsAgo(3),
    installedAt: '2025-12-11',
  },
  {
    id: 'CAM-06',
    vehicleId: 'BUS-441',
    position: 'front',
    route: 'AB Road',
    status: 'online',
    fps: 25,
    lastActive: minsAgo(2),
    installedAt: '2026-01-08',
  },
];

const loc = {
  nh27: {
    lat: 22.7532,
    lng: 75.8937,
    road: 'NH-27, km 14.2',
    city: 'Indore',
    state: 'Madhya Pradesh',
    landmark: 'Near Super Corridor',
    kmMarker: '14.2',
  },
  mg: {
    lat: 22.7196,
    lng: 75.8577,
    road: 'MG Road',
    city: 'Indore',
    state: 'Madhya Pradesh',
    landmark: 'Palasia Square',
  },
  ring: {
    lat: 22.6921,
    lng: 75.8684,
    road: 'Ring Road',
    city: 'Indore',
    state: 'Madhya Pradesh',
    landmark: 'Bhanwarkuan',
  },
  airport: {
    lat: 22.7279,
    lng: 75.8041,
    road: 'Airport Road',
    city: 'Indore',
    state: 'Madhya Pradesh',
    landmark: 'Near Devi Ahilya Airport',
  },
  ab: {
    lat: 22.7533,
    lng: 75.8926,
    road: 'AB Road',
    city: 'Indore',
    state: 'Madhya Pradesh',
    landmark: 'Vijay Nagar',
  },
  rajwada: {
    lat: 22.7186,
    lng: 75.8552,
    road: 'Rajwada Road',
    city: 'Indore',
    state: 'Madhya Pradesh',
    landmark: 'Rajwada',
  },
};

export const detections: Detection[] = [
  {
    id: 'DET-2041',
    incidentId: 'RV-1024',
    cameraId: 'CAM-01',
    vehicleId: 'BUS-204',
    type: 'pothole',
    confidence: 0.94,
    severity: 'critical',
    bbox: { x: 0.42, y: 0.58, w: 0.22, h: 0.16 },
    timestamp: minsAgo(2),
    fps: 24,
    approxSizeCm: 48,
    location: loc.nh27,
  },
  {
    id: 'DET-2044',
    incidentId: 'RV-1024',
    cameraId: 'CAM-04',
    vehicleId: 'BUS-204',
    type: 'pothole',
    confidence: 0.95,
    severity: 'critical',
    bbox: { x: 0.46, y: 0.54, w: 0.2, h: 0.15 },
    timestamp: minsAgo(4),
    fps: 26,
    approxSizeCm: 46,
    location: { ...loc.nh27, lat: 22.7535, lng: 75.8941 },
  },
  {
    id: 'DET-2050',
    incidentId: 'RV-1025',
    cameraId: 'CAM-02',
    vehicleId: 'BUS-118',
    type: 'crack',
    confidence: 0.88,
    severity: 'moderate',
    bbox: { x: 0.3, y: 0.62, w: 0.38, h: 0.1 },
    timestamp: minsAgo(18),
    fps: 22,
    approxSizeCm: 210,
    location: loc.mg,
  },
  {
    id: 'DET-2058',
    incidentId: 'RV-1026',
    cameraId: 'CAM-05',
    vehicleId: 'BUS-332',
    type: 'damage',
    confidence: 0.96,
    severity: 'resolved',
    bbox: { x: 0.36, y: 0.5, w: 0.28, h: 0.2 },
    timestamp: hoursAgo(5),
    fps: 23,
    approxSizeCm: 92,
    location: loc.airport,
  },
  {
    id: 'DET-2061',
    incidentId: 'RV-1027',
    cameraId: 'CAM-06',
    vehicleId: 'BUS-441',
    type: 'pothole',
    confidence: 0.81,
    severity: 'low',
    bbox: { x: 0.52, y: 0.64, w: 0.14, h: 0.1 },
    timestamp: hoursAgo(2),
    fps: 25,
    approxSizeCm: 18,
    location: loc.ab,
  },
  {
    id: 'DET-2066',
    incidentId: 'RV-1028',
    cameraId: 'CAM-02',
    vehicleId: 'BUS-118',
    type: 'depression',
    confidence: 0.91,
    severity: 'moderate',
    bbox: { x: 0.4, y: 0.56, w: 0.24, h: 0.14 },
    timestamp: hoursAgo(7),
    fps: 22,
    approxSizeCm: 64,
    location: loc.rajwada,
  },
  {
    id: 'DET-2070',
    incidentId: 'RV-1029',
    cameraId: 'CAM-06',
    vehicleId: 'BUS-441',
    type: 'marking',
    confidence: 0.79,
    severity: 'low',
    bbox: { x: 0.28, y: 0.7, w: 0.4, h: 0.08 },
    timestamp: hoursAgo(11),
    fps: 25,
    approxSizeCm: 320,
    location: loc.ab,
  },
  {
    id: 'DET-2074',
    incidentId: 'RV-1030',
    cameraId: 'CAM-01',
    vehicleId: 'BUS-204',
    type: 'pothole',
    confidence: 0.97,
    severity: 'critical',
    bbox: { x: 0.38, y: 0.52, w: 0.24, h: 0.18 },
    timestamp: minsAgo(0),
    fps: 24,
    approxSizeCm: 56,
    location: { ...loc.nh27, kmMarker: '14.8', road: 'NH-27, km 14.8', lat: 22.7551, lng: 75.8962 },
  },
];

export const incidents: Incident[] = [
  {
    id: 'RV-1024',
    type: 'pothole',
    confidence: 0.945,
    severity: 'critical',
    status: 'acknowledged',
    location: loc.nh27,
    cameraId: 'CAM-01',
    vehicleId: 'BUS-204',
    timestamp: minsAgo(2),
    approxSizeCm: 48,
    detections: detections.filter((d) => d.incidentId === 'RV-1024'),
    duplicate: {
      comparedId: 'RV-1024',
      cameraA: 'CAM-01',
      cameraB: 'CAM-04',
      detectionA: 'DET-2041',
      detectionB: 'DET-2044',
      similarity: 0.984,
      sameIncident: true,
    },
    complaintId: 'CMP-8812',
    authority: 'Public Works Department',
    division: 'Indore Division 4',
    pipeline: fullPipeline('complaint'),
    notes: 'Deep pothole on carriageway, right lane. Two cameras confirmed same defect.',
  },
  {
    id: 'RV-1025',
    type: 'crack',
    confidence: 0.88,
    severity: 'moderate',
    status: 'sent',
    location: loc.mg,
    cameraId: 'CAM-02',
    vehicleId: 'BUS-118',
    timestamp: minsAgo(18),
    approxSizeCm: 210,
    detections: detections.filter((d) => d.incidentId === 'RV-1025'),
    complaintId: 'CMP-8813',
    authority: 'Indore Municipal Corporation',
    division: 'Zone 8 — Palasia',
    pipeline: fullPipeline('complaint'),
  },
  {
    id: 'RV-1026',
    type: 'damage',
    confidence: 0.96,
    severity: 'resolved',
    status: 'resolved',
    location: loc.airport,
    cameraId: 'CAM-05',
    vehicleId: 'BUS-332',
    timestamp: hoursAgo(5),
    approxSizeCm: 92,
    detections: detections.filter((d) => d.incidentId === 'RV-1026'),
    complaintId: 'CMP-8790',
    authority: 'Public Works Department',
    division: 'Airport Corridor Cell',
    pipeline: fullPipeline('resolution'),
    notes: 'Surface reconstructed. Verified by follow-up scan.',
  },
  {
    id: 'RV-1027',
    type: 'pothole',
    confidence: 0.81,
    severity: 'low',
    status: 'verified',
    location: loc.ab,
    cameraId: 'CAM-06',
    vehicleId: 'BUS-441',
    timestamp: hoursAgo(2),
    approxSizeCm: 18,
    detections: detections.filter((d) => d.incidentId === 'RV-1027'),
    pipeline: fullPipeline('location'),
  },
  {
    id: 'RV-1028',
    type: 'depression',
    confidence: 0.91,
    severity: 'moderate',
    status: 'authority_identified',
    location: loc.rajwada,
    cameraId: 'CAM-02',
    vehicleId: 'BUS-118',
    timestamp: hoursAgo(7),
    approxSizeCm: 64,
    detections: detections.filter((d) => d.incidentId === 'RV-1028'),
    authority: 'Indore Municipal Corporation',
    division: 'Heritage Zone',
    pipeline: fullPipeline('authority'),
  },
  {
    id: 'RV-1029',
    type: 'marking',
    confidence: 0.79,
    severity: 'low',
    status: 'verified',
    location: loc.ab,
    cameraId: 'CAM-06',
    vehicleId: 'BUS-441',
    timestamp: hoursAgo(11),
    approxSizeCm: 320,
    detections: detections.filter((d) => d.incidentId === 'RV-1029'),
    pipeline: fullPipeline('duplicate'),
  },
  {
    id: 'RV-1030',
    type: 'pothole',
    confidence: 0.97,
    severity: 'critical',
    status: 'detected',
    location: { ...loc.nh27, kmMarker: '14.8', road: 'NH-27, km 14.8', lat: 22.7551, lng: 75.8962 },
    cameraId: 'CAM-01',
    vehicleId: 'BUS-204',
    timestamp: minsAgo(0),
    approxSizeCm: 56,
    detections: detections.filter((d) => d.incidentId === 'RV-1030'),
    pipeline: {
      detection: true,
      privacy: true,
      duplicate: false,
      location: true,
      authority: false,
      complaint: false,
      resolution: false,
    },
    notes: 'Live detection. Privacy processed. Duplicate check in progress.',
  },
  {
    id: 'RV-1018',
    type: 'crack',
    confidence: 0.86,
    severity: 'resolved',
    status: 'resolved',
    location: loc.ring,
    cameraId: 'CAM-03',
    vehicleId: 'BUS-091',
    timestamp: hoursAgo(30),
    approxSizeCm: 140,
    detections: [],
    complaintId: 'CMP-8744',
    authority: 'Public Works Department',
    division: 'Ring Road Cell',
    pipeline: fullPipeline('resolution'),
  },
];

export const complaints: Complaint[] = [
  {
    id: 'CMP-8812',
    incidentId: 'RV-1024',
    authority: 'Public Works Department',
    division: 'Indore Division 4',
    status: 'acknowledged',
    createdAt: minsAgo(1),
    updatedAt: minsAgo(1),
    events: [
      { status: 'detected', at: minsAgo(4), note: 'Defect captured by CAM-01 on BUS-204' },
      { status: 'verified', at: minsAgo(3), note: 'Privacy processed. Duplicate confirmed with CAM-04 (98.4%)' },
      { status: 'authority_identified', at: minsAgo(2), note: 'PWD Indore Division 4 assigned via GPS jurisdiction' },
      { status: 'sent', at: minsAgo(2), note: 'Complaint auto-filed with evidence pack' },
      { status: 'acknowledged', at: minsAgo(1), note: 'PWD acknowledged. Crew dispatch pending' },
    ],
  },
  {
    id: 'CMP-8813',
    incidentId: 'RV-1025',
    authority: 'Indore Municipal Corporation',
    division: 'Zone 8 — Palasia',
    status: 'sent',
    createdAt: minsAgo(16),
    updatedAt: minsAgo(16),
    events: [
      { status: 'detected', at: minsAgo(18), note: 'Longitudinal crack detected on MG Road' },
      { status: 'verified', at: minsAgo(17), note: 'AI verification complete. Unique incident.' },
      { status: 'authority_identified', at: minsAgo(16), note: 'IMC Zone 8 identified' },
      { status: 'sent', at: minsAgo(16), note: 'Complaint dispatched to municipal desk' },
    ],
  },
  {
    id: 'CMP-8790',
    incidentId: 'RV-1026',
    authority: 'Public Works Department',
    division: 'Airport Corridor Cell',
    status: 'resolved',
    createdAt: hoursAgo(28),
    updatedAt: hoursAgo(2),
    events: [
      { status: 'detected', at: hoursAgo(30), note: 'Severe surface damage near airport approach' },
      { status: 'verified', at: hoursAgo(29), note: 'Verified unique. Size ~92cm' },
      { status: 'authority_identified', at: hoursAgo(29), note: 'PWD Airport Corridor Cell' },
      { status: 'sent', at: hoursAgo(28), note: 'Priority complaint filed' },
      { status: 'acknowledged', at: hoursAgo(26), note: 'Crew assigned' },
      { status: 'pending', at: hoursAgo(12), note: 'Repair in progress' },
      { status: 'resolved', at: hoursAgo(2), note: 'Resurfaced. Follow-up scan confirmed closure.' },
    ],
    resolutionNote: 'Milling and overlay completed. Follow-up confidence 0.12 (no defect).',
  },
  {
    id: 'CMP-8744',
    incidentId: 'RV-1018',
    authority: 'Public Works Department',
    division: 'Ring Road Cell',
    status: 'resolved',
    createdAt: hoursAgo(48),
    updatedAt: hoursAgo(8),
    events: [
      { status: 'detected', at: hoursAgo(52), note: 'Crack cluster on Ring Road' },
      { status: 'verified', at: hoursAgo(51), note: 'Verified' },
      { status: 'authority_identified', at: hoursAgo(50), note: 'PWD Ring Road Cell' },
      { status: 'sent', at: hoursAgo(48), note: 'Filed' },
      { status: 'acknowledged', at: hoursAgo(40), note: 'Acknowledged' },
      { status: 'pending', at: hoursAgo(20), note: 'Seal coating' },
      { status: 'resolved', at: hoursAgo(8), note: 'Closed after inspection' },
    ],
  },
];

export const metrics = {
  roadsScanned: 247,
  defectsDetected: 38,
  criticalDefects: 12,
  aiConfidence: 0.94,
  resolvedDefects: 19,
  resolutionRate: 0.5,
  avgConfidence: 0.91,
  camerasOnline: 5,
  camerasTotal: 6,
};

export const trend7d = [
  { day: 'Mon', defects: 9, resolved: 4 },
  { day: 'Tue', defects: 12, resolved: 6 },
  { day: 'Wed', defects: 7, resolved: 8 },
  { day: 'Thu', defects: 14, resolved: 5 },
  { day: 'Fri', defects: 11, resolved: 9 },
  { day: 'Sat', defects: 6, resolved: 7 },
  { day: 'Sun', defects: 8, resolved: 5 },
];

export const defectDistribution = [
  { type: 'Potholes', count: 18, colorKey: 'red' as const },
  { type: 'Road Damage', count: 8, colorKey: 'amber' as const },
  { type: 'Cracks', count: 7, colorKey: 'blue' as const },
  { type: 'Other', count: 5, colorKey: 'purple' as const },
];

export const roadHealth = {
  good: 164,
  needsRepair: 71,
  critical: 12,
};

export const defectLabel: Record<string, string> = {
  pothole: 'Pothole',
  crack: 'Road Crack',
  damage: 'Road Damage',
  depression: 'Surface Depression',
  marking: 'Faded Marking',
};

export const severityLabel: Record<string, string> = {
  critical: 'Critical',
  moderate: 'Moderate',
  low: 'Low',
  resolved: 'Resolved',
};

export const statusLabel: Record<string, string> = {
  detected: 'Detected',
  verified: 'Verified',
  authority_identified: 'Authority Identified',
  sent: 'Complaint Sent',
  acknowledged: 'Acknowledged',
  pending: 'Resolution Pending',
  resolved: 'Resolved',
};

export const pipelineLabels: { key: keyof PipelineState; short: string; long: string }[] = [
  { key: 'detection', short: 'Detected', long: 'Camera → Detected' },
  { key: 'privacy', short: 'Privacy', long: 'Privacy Processed' },
  { key: 'duplicate', short: 'Duplicate', long: 'Duplicate Verified' },
  { key: 'location', short: 'Location', long: 'Location Identified' },
  { key: 'authority', short: 'Authority', long: 'Authority Found' },
  { key: 'complaint', short: 'Complaint', long: 'Complaint Sent' },
  { key: 'resolution', short: 'Resolved', long: 'Resolution' },
];
